<a href="https://colab.research.google.com/github/ChoeTaeBin/Machine-Learnig/blob/main/treeEnsemble.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

앙상블학습을 이용하여 성능을 높일 수 있다.

In [2]:
#데이터 준비
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
wine = pd.read_csv('https://bit.ly/wine_csv_data')
data = wine[['alcohol', 'sugar', 'pH']].to_numpy()
target = wine['class'].to_numpy()
train_input, test_input, train_target, test_taget = train_test_split(data, target, test_size = 0.2, random_state = 42)

Random Forest

In [7]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier( n_jobs=-1, random_state = 42)

print('<교차 검증>\n')
scores = cross_validate(rf, train_input, train_target, return_train_score = True, n_jobs = -1) #교차검증을 함
print('train data score: ', np.mean(scores['train_score']))
print('test data score: ', np.mean(scores['test_score']))

print('\n<OOB샘플 이용>')
rf = RandomForestClassifier(oob_score = True, n_jobs=-1, random_state = 42) #OOB샘플을 이용해서 교차검증 처럼 이용할 수 도 있음
rf.fit(train_input, train_target)
print('oob score: ', rf.oob_score_)


<교차 검증>

train data score:  0.9973541965122431
test data score:  0.8905151032797809

<OOB샘플 이용>
oob score:  0.8934000384837406


특성 중요도의 편향이 많이 완화 된다.

In [8]:
#특성 중요도
print(rf.feature_importances_)

[0.23167441 0.50039841 0.26792718]


Extra Trees

In [9]:
from sklearn.ensemble import ExtraTreesClassifier

et = ExtraTreesClassifier(n_jobs = -1, random_state = 42)
scores = cross_validate(et, train_input, train_target, return_train_score=True, n_jobs = -1)

print('train data score: ', np.mean(scores['train_score']))
print('test data score: ', np.mean(scores['test_score']))

et.fit(train_input, train_target)
print('<특성 중요도>\n', et.feature_importances_)

train data score:  0.9974503966084433
test data score:  0.8887848893166506
<특성 중요도>
 [0.20183568 0.52242907 0.27573525]


Gradient Boosting

손실함수값이 줄어드는 방향으로 깊이가 앝은 트리를 계속해서 추가해 나가는 알고리즘이다.

In [10]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(random_state = 42)

scores = cross_validate(gb, train_input, train_target, return_train_score=True, n_jobs = -1)

print('train data score: ', np.mean(scores['train_score']))
print('test data score: ', np.mean(scores['test_score']))

gb.fit(train_input, train_target)
print('<특성 중요도>\n', gb.feature_importances_)

train data score:  0.8881086892152563
test data score:  0.8720430147331015
<특성 중요도>
 [0.11949946 0.74871836 0.13178218]


Histogram-based Gradient Boosting

In [11]:
#sklearn
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingClassifier

hgb = HistGradientBoostingClassifier(random_state = 42)
scores = cross_validate(hgb, train_input, train_target, return_train_score=True, n_jobs = -1)

print('train data score: ', np.mean(scores['train_score']))
print('test data score: ', np.mean(scores['test_score']))

/usr/local/lib/python3.10/dist-packages/sklearn/experimental/enable_hist_gradient_boosting.py:16: UserWarning: Since version 1.0, it is not needed to import enable_hist_gradient_boosting anymore. HistGradientBoostingClassifier and HistGradientBoostingRegressor are now stable and can be normally imported from sklearn.ensemble.
  warnings.warn(


train data score:  0.9321723946453317
test data score:  0.8801241948619236


특성 중요도를 계산하는 최신 방법:
permutation_importance()
idea: 한 특성값을 랜덤으로 섞고 모델을 훈련시킨 후 정상적인 샘플과 비교했을때 얼마나 점수가 떨어졌는지 보면 그 특성이 얼마나 중요한지 알 수 있다.

In [12]:
from sklearn.inspection import permutation_importance

hgb.fit(train_input, train_target)
result = permutation_importance(hgb, train_input, train_target, n_repeats = 10, random_state=42, n_jobs=-1)
print(result.importances_mean)

[0.08876275 0.23438522 0.08027708]


In [13]:
#XGBoost
from xgboost import XGBClassifier
xgb = XGBClassifier(tree_method='hist', random_state=42)

scores = cross_validate(xgb, train_input, train_target, return_train_score=True, n_jobs = -1)

print('train data score: ', np.mean(scores['train_score']))
print('test data score: ', np.mean(scores['test_score']))

train data score:  0.9558403027491312
test data score:  0.8782000074035686


In [15]:
from lightgbm import LGBMClassifier
lgb = LGBMClassifier(random_state = 42)

scores = cross_validate(lgb, train_input, train_target, return_train_score=True, n_jobs = -1)

print('train data score: ', np.mean(scores['train_score']))
print('test data score: ', np.mean(scores['test_score']))

train data score:  0.935828414851749
test data score:  0.8801251203079884
